# -*- coding: utf-8 -*-
"""BarPieChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvYQAXsGOS4IFgxF4tDfEzJO5_xxxHvW
"""

import matplotlib.pyplot as plt
import pandas as pd
from collections import Counter

path = ("/content/drive/MyDrive/Artificial Intelligence/Final Project")
pathcsv = 'static/dataRecord/csv/'
visualPath = 'static/dataRecord/visualization/'

def visualization(filename):
    df = pd.read_csv(pathcsv+f"{filename}.csv")

    data = df['Ekspresi']

    counter = Counter(data)

    counts = list(counter.items())

    bar_labels = [x[0] for x in counts]
    bar_values = [x[1] for x in counts]
    pie_labels = [x[0] for x in counts]
    pie_values = [x[1] for x in counts]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    #Bar Chart
    ax1.bar(bar_labels, bar_values, color ='blue',
            width = 0.7)

    ax1.set_title('Bar Chart')

    #Pie Chart
    ax2.pie(pie_values, labels=pie_labels, autopct='%1.1f%%')

    ax2.set_title('Pie Chart')

    # plt.show()
    saveFig = plt.savefig(f"{visualPath}{filename}.png", format='png')

    return saveFig